apiVersion: apps/v1
kind: Deployment
metadata:
  name: cloudl-client-deployment
spec:
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  minReadySeconds: 5
  template:
    metadata:
      labels:
        app: cloudl-client
    spec:
      containers:
        - name: cloudl-client
          image: lancloud/frontend:v2
          ports:
            - containerPort: 80
              name: http-port
          resources:
            requests:
              cpu: 100m
            limits:
              cpu: 150m
  selector:
    matchLabels:
      app: cloudl-client
